"""Slack channel collection into dated, evidence-ready Markdown sources."""

from __future__ import annotations

import datetime as dt
import json
import os
import re
import socket
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

from .errors import AuthenticationError, ConfigurationError, StorageError, TransientExtractionError
from .util import atomic_write, dump_frontmatter, local_timezone, slugify


GENERATED_MARKER = "<!-- GENERATED BY MEETING-MEMORY SLACK SYNC -->"
AUTH_ERRORS = {
    "account_inactive",
    "invalid_auth",
    "not_authed",
    "token_expired",
    "token_revoked",
}


class SlackApiError(ConfigurationError):
    """Slack returned a structured application error."""

    def __init__(self, code: str):
        super().__init__("Slack API failure: %s" % code)
        self.code = code


class SlackWebClient:
    """Small stdlib Slack Web API client with structured error classification."""

    endpoint = "https://slack.com/api/"

    def __init__(self, token: str, timeout: int = 60):
        if not token:
            raise ConfigurationError("Slack channel_ids are configured but no bot token is available")
        self.token = token
        self.timeout = timeout

    def call(self, method: str, params: Mapping[str, Any]) -> Dict[str, Any]:
        query = urllib.parse.urlencode(
            {key: str(value).lower() if isinstance(value, bool) else value for key, value in params.items()}
        )
        request = urllib.request.Request(
            self.endpoint + method + "?" + query,
            headers={
                "Authorization": "Bearer %s" % self.token,
                "Accept": "application/json",
                "User-Agent": "meeting-memory/0.1",
            },
            method="GET",
        )
        try:
            with urllib.request.urlopen(request, timeout=self.timeout) as response:
                payload = response.read().decode("utf-8")
        except urllib.error.HTTPError as exc:
            if exc.code == 429 or 500 <= exc.code < 600:
                raise TransientExtractionError("temporary Slack API HTTP failure: %s" % exc.code) from exc
            if exc.code in (401, 403):
                raise AuthenticationError("Slack rejected the configured token") from exc
            raise ConfigurationError("Slack API HTTP failure: %s" % exc.code) from exc
        except (urllib.error.URLError, socket.timeout, TimeoutError) as exc:
            raise TransientExtractionError("temporary Slack API connection failure: %s" % exc) from exc
        try:
            raw = json.loads(payload)
        except ValueError as exc:
            raise TransientExtractionError("Slack returned invalid JSON") from exc
        if not isinstance(raw, dict):
            raise TransientExtractionError("Slack returned an invalid response object")
        if not raw.get("ok"):
            code = str(raw.get("error") or "unknown_error")
            if code in AUTH_ERRORS:
                raise AuthenticationError("Slack authentication failure: %s" % code)
            if code in {
                "fatal_error",
                "internal_error",
                "ratelimited",
                "request_timeout",
                "service_unavailable",
                "team_added_to_org",
            }:
                raise TransientExtractionError("temporary Slack API failure: %s" % code)
            raise SlackApiError(code)
        return raw


@dataclass
class SlackSyncResult:
    channels: int
    dates: List[str]
    messages: int
    files_changed: List[str]
    files_unchanged: List[str]
    dry_run: bool

    def to_dict(self) -> Dict[str, Any]:
        return {
            "channels": self.channels,
            "dates": self.dates,
            "messages": self.messages,
            "files_changed": self.files_changed,
            "files_unchanged": self.files_unchanged,
            "dry_run": self.dry_run,
        }


def _timestamp(value: str) -> dt.datetime:
    try:
        return dt.datetime.fromtimestamp(float(value), tz=dt.timezone.utc)
    except (TypeError, ValueError, OverflowError) as exc:
        raise SlackApiError("invalid_message_timestamp") from exc


def _next_cursor(raw: Mapping[str, Any]) -> str:
    metadata = raw.get("response_metadata") or {}
    if not isinstance(metadata, dict):
        return ""
    return str(metadata.get("next_cursor") or "").strip()


def _message_identity(message: Mapping[str, Any]) -> str:
    # Slack timestamps uniquely identify messages inside a conversation. A
    # parent returned by both history and replies therefore collapses cleanly
    # even when one representation omits client_msg_id.
    return str(message.get("ts") or "")


class SlackCollector:
    """Collect configured channels and materialize one deterministic note per day/channel."""

    def __init__(
        self,
        meetings_dir: Path,
        channel_ids: Sequence[str],
        token: Optional[str] = None,
        client: Optional[Any] = None,
        local_tz: Optional[dt.timezone] = None,
    ):
        self.meetings_dir = Path(meetings_dir).resolve()
        self.channel_ids = list(dict.fromkeys(channel_ids))
        invalid = [value for value in self.channel_ids if not re.fullmatch(r"[CDG][A-Z0-9]+", value)]
        if invalid:
            raise ConfigurationError("invalid Slack channel ID: %s" % invalid[0])
        resolved_token = token or os.environ.get("SLACK_BOT_TOKEN") or os.environ.get("SLACK_TOKEN")
        self.client = client or (SlackWebClient(resolved_token or "") if self.channel_ids else None)
        self.local_tz = local_tz or local_timezone()
        self._user_names: Dict[str, str] = {}

    def _pages(self, method: str, params: Dict[str, Any]) -> Iterable[Dict[str, Any]]:
        cursor = ""
        seen = set()
        while True:
            request_params = dict(params)
            if cursor:
                request_params["cursor"] = cursor
            raw = self.client.call(method, request_params)
            yield raw
            cursor = _next_cursor(raw)
            if not cursor:
                return
            if cursor in seen:
                raise TransientExtractionError("Slack pagination returned a repeated cursor")
            seen.add(cursor)

    def _history(self, channel_id: str, start: dt.datetime, end: dt.datetime) -> List[Dict[str, Any]]:
        messages: Dict[str, Dict[str, Any]] = {}
        params = {
            "channel": channel_id,
            "oldest": "%.6f" % start.timestamp(),
            "latest": "%.6f" % end.timestamp(),
            "inclusive": True,
            "limit": 200,
            "include_all_metadata": True,
        }
        parents = []
        for page in self._pages("conversations.history", params):
            raw_messages = page.get("messages") or []
            if not isinstance(raw_messages, list):
                raise TransientExtractionError("Slack history response has invalid messages")
            for message in raw_messages:
                if not isinstance(message, dict) or not message.get("ts"):
                    continue
                observed = _timestamp(str(message["ts"]))
                if start <= observed < end:
                    messages[_message_identity(message)] = message
                if message.get("reply_count") and not message.get("thread_ts"):
                    parents.append(str(message["ts"]))
                elif message.get("reply_count") and str(message.get("thread_ts")) == str(message["ts"]):
                    parents.append(str(message["ts"]))

        for thread_ts in dict.fromkeys(parents):
            try:
                pages = self._pages(
                    "conversations.replies",
                    {"channel": channel_id, "ts": thread_ts, "limit": 200},
                )
                for page in pages:
                    replies = page.get("messages") or []
                    if not isinstance(replies, list):
                        raise TransientExtractionError("Slack replies response has invalid messages")
                    for reply in replies:
                        if not isinstance(reply, dict) or not reply.get("ts"):
                            continue
                        observed = _timestamp(str(reply["ts"]))
                        if start <= observed < end:
                            messages[_message_identity(reply)] = reply
            except SlackApiError as exc:
                if exc.code != "thread_not_found":
                    raise
        return sorted(messages.values(), key=lambda item: (float(str(item["ts"])), _message_identity(item)))

    def _user_name(self, user_id: str) -> str:
        if not user_id:
            return "unknown"
        if user_id in self._user_names:
            return self._user_names[user_id]
        name = user_id
        try:
            raw = self.client.call("users.info", {"user": user_id})
            user = raw.get("user") or {}
            profile = user.get("profile") or {} if isinstance(user, dict) else {}
            if isinstance(profile, dict):
                name = str(
                    profile.get("display_name")
                    or profile.get("real_name")
                    or (user.get("name") if isinstance(user, dict) else "")
                    or user_id
                )
        except SlackApiError as exc:
            if exc.code not in {"missing_scope", "user_not_found", "users_not_found"}:
                raise
        self._user_names[user_id] = name
        return name

    @staticmethod
    def _block_text(value: Any) -> List[str]:
        """Flatten common Block Kit/rich-text nodes without depending on an SDK."""
        if isinstance(value, list):
            result = []
            for item in value:
                result.extend(SlackCollector._block_text(item))
            return result
        if not isinstance(value, dict):
            return []
        kind = value.get("type")
        if kind == "user" and value.get("user_id"):
            return ["<@%s>" % value["user_id"]]
        if kind == "emoji" and value.get("name"):
            return [":%s:" % value["name"]]
        if kind == "link" and value.get("url"):
            label = value.get("text")
            return ["%s (%s)" % (label, value["url"]) if label else str(value["url"])]
        result = []
        text = value.get("text")
        if isinstance(text, str) and text.strip():
            result.append(text.strip())
        elif isinstance(text, (dict, list)):
            result.extend(SlackCollector._block_text(text))
        for key in ("fields", "elements"):
            result.extend(SlackCollector._block_text(value.get(key)))
        return result

    @staticmethod
    def _message_text(message: Mapping[str, Any]) -> str:
        parts = []
        text = message.get("text")
        if isinstance(text, str) and text.strip():
            parts.append(text.strip())
        block_text = " ".join(SlackCollector._block_text(message.get("blocks"))).strip()
        if block_text and block_text not in parts:
            parts.append(block_text)
        attachments = message.get("attachments") or []
        if isinstance(attachments, list):
            for attachment in attachments:
                if not isinstance(attachment, dict):
                    continue
                values = [attachment.get(key) for key in ("pretext", "title", "text", "fallback")]
                rendered = " — ".join(str(value).strip() for value in values if isinstance(value, str) and value.strip())
                if rendered and rendered not in parts:
                    parts.append(rendered)
        files = message.get("files") or []
        if isinstance(files, list):
            for item in files:
                if not isinstance(item, dict):
                    continue
                label = str(item.get("title") or item.get("name") or item.get("id") or "Slack file")
                url = item.get("permalink")
                parts.append("File: %s%s" % (label, " (%s)" % url if url else ""))
        reactions = message.get("reactions") or []
        if isinstance(reactions, list):
            rendered_reactions = []
            for reaction in reactions:
                if isinstance(reaction, dict) and reaction.get("name"):
                    rendered_reactions.append(
                        ":%s: ×%s" % (reaction["name"], reaction.get("count", 1))
                    )
            if rendered_reactions:
                parts.append("Reactions: %s" % ", ".join(rendered_reactions))
        return "\n\n".join(parts) or "_(Slack event with no text)_"

    def _render(self, channel_id: str, source_date: str, messages: Sequence[Mapping[str, Any]]) -> bytes:
        frontmatter = dump_frontmatter(
            {
                "title": "Slack channel %s — %s" % (channel_id, source_date),
                "date": source_date,
                "source_type": "slack",
                "slack_channel_id": channel_id,
                "durable_knowledge": bool(messages),
                "generated_by": "meeting-memory",
            }
        )
        sections = []
        for message in messages:
            observed = _timestamp(str(message["ts"])).astimezone(self.local_tz)
            user_id = str(message.get("user") or message.get("bot_id") or "")
            bot_profile = message.get("bot_profile") or {}
            bot_name = bot_profile.get("name") if isinstance(bot_profile, dict) else None
            author_name = str(bot_name or message.get("username") or self._user_name(user_id))
            author = "%s (%s)" % (author_name, user_id) if user_id and author_name != user_id else author_name
            lines = [
                "## %s — %s" % (observed.strftime("%H:%M:%S %Z"), author),
                "",
                "- Slack timestamp: `%s`" % message["ts"],
            ]
            thread_ts = message.get("thread_ts")
            if thread_ts and str(thread_ts) != str(message["ts"]):
                lines.append("- Thread parent: `%s`" % thread_ts)
            if message.get("edited"):
                edited = message.get("edited") or {}
                if isinstance(edited, dict) and edited.get("ts"):
                    lines.append("- Edited at: `%s`" % edited["ts"])
            lines.extend(["", self._message_text(message)])
            sections.append("\n".join(lines))
        body = "\n\n".join(sections) if sections else "_No Slack messages in this local calendar day._"
        return ("---\n%s\n---\n\n%s\n\n# Slack channel %s — %s\n\n%s\n" % (
            frontmatter,
            GENERATED_MARKER,
            channel_id,
            source_date,
            body,
        )).encode("utf-8")

    def _target_path(self, channel_id: str, source_date: str) -> Path:
        path = self.meetings_dir / source_date / ("slack-%s.md" % slugify(channel_id, 48))
        try:
            path.parent.resolve().relative_to(self.meetings_dir)
        except ValueError as exc:
            raise StorageError("Slack source target escapes meeting directory: %s" % path) from exc
        return path

    @staticmethod
    def _safe_existing(path: Path) -> None:
        if not path.exists():
            return
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeError) as exc:
            raise StorageError("cannot inspect existing Slack source %s: %s" % (path, exc)) from exc
        if GENERATED_MARKER not in text:
            raise StorageError("refusing to overwrite non-generated source: %s" % path)

    def sync(self, start_date: dt.date, end_date: dt.date, dry_run: bool = False) -> SlackSyncResult:
        """Synchronize the half-open local-calendar-day interval [start_date, end_date)."""
        if end_date <= start_date:
            raise ValueError("Slack sync end date must be after start date")
        dates = []
        current = start_date
        while current < end_date:
            dates.append(current.isoformat())
            current += dt.timedelta(days=1)
        if not self.channel_ids:
            return SlackSyncResult(0, dates, 0, [], [], dry_run)

        start = dt.datetime.combine(start_date, dt.time.min, tzinfo=self.local_tz)
        end = dt.datetime.combine(end_date, dt.time.min, tzinfo=self.local_tz)
        by_channel_date: Dict[Tuple[str, str], List[Dict[str, Any]]] = {}
        total_messages = 0
        for channel_id in self.channel_ids:
            messages = self._history(channel_id, start, end)
            total_messages += len(messages)
            for source_date in dates:
                by_channel_date[(channel_id, source_date)] = []
            for message in messages:
                source_date = _timestamp(str(message["ts"])).astimezone(self.local_tz).date().isoformat()
                by_channel_date[(channel_id, source_date)].append(message)

        changed = []
        unchanged = []
        writes: List[Tuple[Path, bytes]] = []
        for (channel_id, source_date), messages in sorted(by_channel_date.items()):
            path = self._target_path(channel_id, source_date)
            self._safe_existing(path)
            data = self._render(channel_id, source_date, messages)
            relative = path.relative_to(self.meetings_dir).as_posix()
            if path.exists() and path.read_bytes() == data:
                unchanged.append(relative)
            else:
                changed.append(relative)
                writes.append((path, data))
        if not dry_run:
            for path, data in writes:
                atomic_write(path, data)
        return SlackSyncResult(
            len(self.channel_ids), dates, total_messages, changed, unchanged, dry_run
        )
